version: '3.8'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: onepips
    ports:
      - "5432:5432"

  api:
    build: .
    ports:
      - "3001:3001"
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql://postgres:password@db:5432/onepips"
      JWT_SECRET: "your-secret-key"
      STRIPE_SECRET_KEY: "your-stripe-key"