version: '3.8'

services:
  db:
    image: postgres:15
    container_name: onepips-db
    restart: always
    environment:
      POSTGRES_USER: onepips
      POSTGRES_PASSWORD: onepips1998
      POSTGRES_DB: onepips
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: